# Generated by Django 4.2.4 on 2023-08-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_vaccinationcenter_id_slot"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
